jobs:
  test:
    executor:
      name: node/default
      tag: '14.15.1'
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
