jobs:
  test:
    docker:
      - image: circleci/node:14.15.1-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test:circle-ci
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
